# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bef2dbac474eec462f8b0026c6767d0f67c84f512656d0db4c1b941e3a56a9f151cd69dffc92ccfbaedf7a3ae99baeb33b616fd2946163c18a608b5a92833a77

test:
  secret_key_base: a901adcdf02e663272aee1297a460036d9b3841d2965e453a3742d400db8f1579544030f01183de822b1de747366d21a10a9616e0378a4667c325622d9f8e9c4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
